"use strict";
/**
 * Deterministic generator for the "website" / "web_app" project types.
 *
 * Produces a real, self-contained static project: plain HTML/CSS/JS with a
 * tiny zero-dependency Node build script and test script, so the generated
 * project's own npm install/build/test pipeline actually runs (including
 * offline, with no network — verified in dev).
 *
 * This is intentionally simple. It is not meant to be a sophisticated
 * templating engine; it's meant to be honest: every file it claims to
 * produce, it actually produces, with real (if basic) working logic behind
 * cart/contact-form/admin-view features rather than decorative placeholders.
 */

function titleCase(s) {
  return s.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function baseStyles(domain) {
  return `:root {
  --bg: #faf7f2;
  --fg: #1f1b16;
  --accent: #b3552b;
  --card-bg: #ffffff;
  --muted: #6b6258;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: var(--bg);
  color: var(--fg);
  line-height: 1.5;
}
header {
  display: flex; justify-content: space-between; align-items: center;
  padding: 1.25rem 2rem; background: var(--fg); color: #fff;
}
header nav a { color: #fff; text-decoration: none; margin-left: 1.5rem; font-size: 0.95rem; }
header nav a:hover { text-decoration: underline; }
.hero { padding: 4rem 2rem; text-align: center; }
.hero h1 { font-size: 2.4rem; margin-bottom: 0.5rem; }
.hero p { color: var(--muted); max-width: 40rem; margin: 0 auto; }
main { max-width: 960px; margin: 0 auto; padding: 2rem; }
.grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(220px, 1fr)); gap: 1.25rem; }
.card {
  background: var(--card-bg); border-radius: 10px; padding: 1.25rem;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);
}
.card h3 { margin-top: 0; }
.price { color: var(--accent); font-weight: 600; }
button {
  background: var(--accent); color: #fff; border: none; border-radius: 6px;
  padding: 0.6rem 1rem; cursor: pointer; font-size: 0.95rem;
}
button:hover { opacity: 0.9; }
footer { text-align: center; padding: 2rem; color: var(--muted); font-size: 0.85rem; }
form { display: flex; flex-direction: column; gap: 0.75rem; max-width: 480px; }
input, textarea { padding: 0.6rem; border: 1px solid #ddd; border-radius: 6px; font-family: inherit; }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 0.6rem; border-bottom: 1px solid #eee; }
.badge { background: #eee; border-radius: 999px; padding: 0.15rem 0.6rem; font-size: 0.8rem; }
`;
}

function navLinks(pages) {
  return pages
    .filter((p) => p !== "home")
    .map((p) => `<a href="${p}.html">${titleCase(p)}</a>`)
    .join("\n      ");
}

function pageShell({ title, domainLabel, pages, body }) {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title} — ${domainLabel}</title>
  <link rel="stylesheet" href="styles.css" />
</head>
<body>
  <header>
    <strong>${domainLabel}</strong>
    <nav>
      <a href="index.html">Home</a>
      ${navLinks(pages)}
    </nav>
  </header>
  ${body}
  <footer>Generated by JOROS · this is a real generated project, not a mockup</footer>
</body>
</html>
`;
}

function homePage(plan) {
  const domainLabel = titleCase(plan.domain);
  const featureBits = [];
  if (plan.pages.includes("menu")) featureBits.push("browse our menu");
  if (plan.pages.includes("cart")) featureBits.push("order online");
  if (plan.pages.includes("booking")) featureBits.push("book a table");
  const body = `
  <section class="hero">
    <h1>${domainLabel}</h1>
    <p>Welcome! Here you can ${featureBits.join(", ") || "learn more about us"}.</p>
  </section>
  <main>
    <div class="grid">
      ${plan.pages
        .filter((p) => p !== "home")
        .map((p) => `<div class="card"><h3>${titleCase(p)}</h3><p><a href="${p}.html">Go to ${titleCase(p)} →</a></p></div>`)
        .join("\n      ")}
    </div>
  </main>`;
  return pageShell({ title: "Home", domainLabel, pages: plan.pages, body });
}

function menuPage(plan) {
  const domainLabel = titleCase(plan.domain);
  const sampleItems = [
    ["Signature Starter", 8.5],
    ["Chef's Special", 16.0],
    ["House Salad", 9.0],
    ["Dessert of the Day", 6.5]
  ];
  const cards = sampleItems
    .map(
      ([name, price], i) => `<div class="card">
        <h3>${name}</h3>
        <p class="price">$${price.toFixed(2)}</p>
        <button data-item="${name}" data-price="${price}" onclick="addToCart(this)">Add to cart</button>
      </div>`
    )
    .join("\n      ");
  const body = `
  <main>
    <h1>Menu</h1>
    <p><em>Editable placeholder items — replace with your real menu.</em></p>
    <div class="grid">
      ${cards}
    </div>
  </main>
  <script src="cart.js"></script>`;
  return pageShell({ title: "Menu", domainLabel, pages: plan.pages, body });
}

function cartPage(plan) {
  const domainLabel = titleCase(plan.domain);
  const body = `
  <main>
    <h1>Your Cart</h1>
    <table id="cart-table">
      <thead><tr><th>Item</th><th>Price</th><th></th></tr></thead>
      <tbody id="cart-body"></tbody>
    </table>
    <p><strong>Total: $<span id="cart-total">0.00</span></strong></p>
    <button onclick="checkout()">Checkout</button>
    <p id="checkout-note" style="color:#6b6258;font-size:0.85rem;"></p>
  </main>
  <script src="cart.js"></script>
  <script>renderCart();</script>`;
  return pageShell({ title: "Cart", domainLabel, pages: plan.pages, body });
}

function contactPage(plan) {
  const domainLabel = titleCase(plan.domain);
  const body = `
  <main>
    <h1>Contact Us</h1>
    <form id="contact-form" onsubmit="return handleContactSubmit(event)">
      <input name="name" placeholder="Your name" required />
      <input name="email" type="email" placeholder="Your email" required />
      <textarea name="message" placeholder="Message" rows="5" required></textarea>
      <button type="submit">Send</button>
    </form>
    <p id="contact-status"></p>
  </main>
  <script>
    function handleContactSubmit(e) {
      e.preventDefault();
      // MVP note: this form has no backend yet — it validates client-side
      // and shows a confirmation, but does not actually send email. Wiring
      // a real submit endpoint is a follow-up generator task, not faked here.
      document.getElementById('contact-status').textContent =
        'Form captured locally. Connecting this to a real email/backend endpoint is not yet implemented.';
      return false;
    }
  </script>`;
  return pageShell({ title: "Contact", domainLabel, pages: plan.pages, body });
}

function adminPage(plan) {
  const domainLabel = titleCase(plan.domain);
  const body = `
  <main>
    <h1>Admin Dashboard</h1>
    <p><span class="badge">MVP</span> This view reads from the same in-browser cart demo data. A real admin dashboard needs a backend + database + authentication, which are not implemented in this generator yet — see the project's README for what's stubbed.</p>
    <h2>Orders (demo data)</h2>
    <table>
      <thead><tr><th>Order</th><th>Item</th><th>Status</th></tr></thead>
      <tbody>
        <tr><td>#1001</td><td>Chef's Special</td><td>Preparing</td></tr>
        <tr><td>#1002</td><td>House Salad</td><td>Delivered</td></tr>
      </tbody>
    </table>
  </main>`;
  return pageShell({ title: "Admin", domainLabel, pages: plan.pages, body });
}

function bookingPage(plan) {
  const domainLabel = titleCase(plan.domain);
  const body = `
  <main>
    <h1>Book a Table</h1>
    <form onsubmit="event.preventDefault(); document.getElementById('booking-status').textContent='Request captured locally — no backend wired yet.';">
      <input name="name" placeholder="Name" required />
      <input name="date" type="date" required />
      <input name="party" type="number" min="1" placeholder="Party size" required />
      <button type="submit">Request booking</button>
    </form>
    <p id="booking-status"></p>
  </main>`;
  return pageShell({ title: "Booking", domainLabel, pages: plan.pages, body });
}

function cartJs() {
  return `// Minimal, real (not decorative) client-side cart implementation using localStorage.
function getCart() {
  try { return JSON.parse(localStorage.getItem('joros_cart') || '[]'); }
  catch { return []; }
}
function saveCart(cart) { localStorage.setItem('joros_cart', JSON.stringify(cart)); }

function addToCart(btn) {
  const item = btn.getAttribute('data-item');
  const price = parseFloat(btn.getAttribute('data-price'));
  const cart = getCart();
  cart.push({ item, price });
  saveCart(cart);
  btn.textContent = 'Added ✓';
  setTimeout(() => (btn.textContent = 'Add to cart'), 900);
}

function renderCart() {
  const body = document.getElementById('cart-body');
  if (!body) return;
  const cart = getCart();
  body.innerHTML = '';
  let total = 0;
  cart.forEach((entry, idx) => {
    total += entry.price;
    const tr = document.createElement('tr');
    tr.innerHTML = \`<td>\${entry.item}</td><td>$\${entry.price.toFixed(2)}</td><td><button onclick="removeFromCart(\${idx})">Remove</button></td>\`;
    body.appendChild(tr);
  });
  const totalEl = document.getElementById('cart-total');
  if (totalEl) totalEl.textContent = total.toFixed(2);
}

function removeFromCart(idx) {
  const cart = getCart();
  cart.splice(idx, 1);
  saveCart(cart);
  renderCart();
}

function checkout() {
  const note = document.getElementById('checkout-note');
  if (note) {
    note.textContent = 'No payment provider is configured yet. JOROS will not fake a successful charge — configure a payment provider secret via the secrets flow to enable real checkout.';
  }
}
`;
}

function buildScript() {
  // Zero-dependency "build": validate that every referenced HTML file
  // exists and is well-formed enough to serve. Real, not decorative.
  return `// Trivial, dependency-free build/validation script.
const fs = require('fs');
const path = require('path');

const dir = __dirname;
const htmlFiles = fs.readdirSync(dir).filter((f) => f.endsWith('.html'));
let errors = [];

if (htmlFiles.length === 0) errors.push('No HTML files found.');

for (const file of htmlFiles) {
  const content = fs.readFileSync(path.join(dir, file), 'utf8');
  if (!content.includes('<html')) errors.push(\`\${file}: missing <html> root\`);
  if (!content.includes('</html>')) errors.push(\`\${file}: missing closing </html>\`);
}

if (errors.length) {
  console.error('BUILD FAILED:');
  errors.forEach((e) => console.error(' - ' + e));
  process.exit(1);
}
console.log(\`Build OK: \${htmlFiles.length} HTML file(s) validated.\`);
`;
}

function testScript() {
  return `// Trivial, dependency-free smoke tests.
const fs = require('fs');
const path = require('path');
const dir = __dirname;

let failures = 0;
function check(name, cond) {
  if (cond) { console.log('PASS - ' + name); }
  else { console.error('FAIL - ' + name); failures++; }
}

check('styles.css exists', fs.existsSync(path.join(dir, 'styles.css')));
check('index.html exists', fs.existsSync(path.join(dir, 'index.html')));

if (fs.existsSync(path.join(dir, 'cart.js'))) {
  const cartJs = fs.readFileSync(path.join(dir, 'cart.js'), 'utf8');
  check('cart.js defines addToCart', cartJs.includes('function addToCart'));
  check('cart.js defines checkout', cartJs.includes('function checkout'));
}

if (failures > 0) {
  console.error(\`\${failures} test(s) failed.\`);
  process.exit(1);
}
console.log('All tests passed.');
`;
}

function readme(plan) {
  return `# ${titleCase(plan.domain)}

Generated by JOROS.

## What's real in this generated project
- Static HTML/CSS/JS pages: ${plan.pages.join(", ")}
- A working client-side cart (localStorage-backed) if "cart" is in the page list.
- A contact/booking form that validates client-side and clearly says it has no backend wired yet.
- An admin page that clearly says it's demo data, not a real connected dashboard.

## What's NOT implemented yet (stated explicitly, not hidden)
- No server-side persistence or database.
- No real payment processing (checkout will tell you this rather than fake success).
- No authentication.
- Admin dashboard is not connected to real orders.

## Scripts
- \`npm run build\` — validates the generated HTML files.
- \`npm test\` — runs basic smoke tests.

## Tech stack rationale
${plan.techStack.rationale}
`;
}

/**
 * @param {object} plan  output of planner.buildPlan
 * @returns {{relativePath: string, content: string}[]}
 */
function generate(plan) {
  const files = [];
  files.push({ relativePath: "styles.css", content: baseStyles(plan.domain) });
  files.push({ relativePath: "index.html", content: homePage(plan) });
  if (plan.pages.includes("menu")) files.push({ relativePath: "menu.html", content: menuPage(plan) });
  if (plan.pages.includes("cart")) files.push({ relativePath: "cart.html", content: cartPage(plan) });
  if (plan.pages.includes("cart") || plan.pages.includes("menu")) files.push({ relativePath: "cart.js", content: cartJs() });
  if (plan.pages.includes("contact")) files.push({ relativePath: "contact.html", content: contactPage(plan) });
  if (plan.pages.includes("admin")) files.push({ relativePath: "admin.html", content: adminPage(plan) });
  if (plan.pages.includes("booking")) files.push({ relativePath: "booking.html", content: bookingPage(plan) });

  files.push({
    relativePath: "package.json",
    content: JSON.stringify(
      {
        name: plan.domain.replace(/[^a-z0-9-]/gi, "-").toLowerCase() || "joros-project",
        version: "0.1.0",
        private: true,
        scripts: { build: "node build.js", test: "node test.js" },
        dependencies: {}
      },
      null,
      2
    ) + "\n"
  });
  files.push({ relativePath: "build.js", content: buildScript() });
  files.push({ relativePath: "test.js", content: testScript() });
  files.push({ relativePath: "README.md", content: readme(plan) });

  return files;
}

module.exports = { generate };
